### ISSUE TITLE
Missing dns dependency

### ISSUE THREAD

**Issue by jajvisser** [immobiliare/dats#365]
After installing and running in NextJS i get the following error on startup

```
../../node_modules/@immobiliarelabs/dats/dist/dns-cache.js:3:0
Module not found: Can't resolve 'dns'

Import trace for requested module:
../../node_modules/@immobiliarelabs/dats/dist/socket.js
../../node_modules/@immobiliarelabs/dats/dist/index.js
```

**Comment by simonecorsi** [comment]
Hi @jajvisser 👋 

`dns` is part of the Node.js standard library, if you want to use this package in Next.js you'll have to use it only on the server-side, eg: `getServerSideProps`

**Comment by jajvisser** [comment]
Hi, thanks for pointing me in the right direction. 

The problem lies a bit deeper, the package is always included in the build to the frontend. Bable always includes it in the build. Only using it in `getServerSideProps` won't work.

I'm currently looking at excluding the package from the frontend build. 

```next.config.ts
  webpack: (config, { isServer, webpack }) => {
    if (!isServer) {
      config.plugins.push(new webpack.IgnorePlugin({ resourceRegExp: /\@immobiliarelabs/ }))
    }
    return config
  },
```

Unfortunatly this is not a working solution for the project setup we are running (a mono repo). But i'm getting there.

**Comment by jajvisser** [comment]
Yes, my solution above works
