### ISSUE TITLE
Refactor timed tests to be more deterministic

### ISSUE THREAD

**Issue by simonecorsi** [immobiliare/dats#38]

**Comment by dnlup** [comment]
We can try using the fake timers of sinon

**Comment by dnlup** [comment]
Could you point me to a failing test? I'd like to start working on it 😉

**Comment by simonecorsi** [comment]
> Could you point me to a failing test? I'd like to start working on it 😉

https://github.com/immobiliare/dats/runs/4150013744?check_suite_focus=true
