### ISSUE TITLE
Call onError when there is a metric with a float number 

### ISSUE THREAD

**Issue by antoniomuso** [immobiliare/dats#46]
We don't check that the metrics should be an integer; we can do it by calling onError if not integer.

**Comment by simonecorsi** [comment]
I won't use `onError` becuase it an user definable callback, we don't know how they are handled externally, we may cause problems!

I think a simple warn in console should be good, it's the end user who must then handle the parsing!

**Comment by antoniomuso** [comment]
But in general, you have to handle it; if you don't do that, it's your problem.

**Comment by simonecorsi** [comment]
But I'm not sure this has to be threated as an Error, statsd as a Proxy support floating point, it could be the pluggable storage that we use that doesn't support it or either a misconfiguration of Grafana

**Comment by antoniomuso** [comment]
As discussed, we can use debug to alert the user in not production environment.

**Comment by simonecorsi** [comment]
lgtm
