### ISSUE TITLE
ESLint and Prettier mismatch 

### ISSUE THREAD

**Issue by antoniomuso** [immobiliare/dats#61]
Eslint and prettier change continuously the code, in particular they change this line of code:
```ts
    const cachable = (ttl, hostname) =>
        buildLookupFunction(ttl, hostname, (mock as unknown) as typeof lookup);
```
For prettier this code it is fine, but Eslint removes the parentesis:
```ts
    const cachable = (ttl, hostname) =>
        buildLookupFunction(ttl, hostname, mock as unknown as typeof lookup);
```

**Comment by simonecorsi** [comment]
I'll give a look, that surely some config set/plugin clashing
