### ISSUE TITLE
Add snyk

### ISSUE THREAD

**Issue by antoniomuso** [immobiliare/dats#79]
We can add [snyk](https://docs.snyk.io/features/integrations/git-repository-scm-integrations/github-integration) in this project.

**Comment by simonecorsi** [comment]
Seems like a nice idea, let me take a look at features and plans just to have a rough idea of what we need.

**Comment by simonecorsi** [comment]
Check if we can use it with the organization, or do we have to use a plan or something!

**Comment by antoniomuso** [comment]
We added it!
